Return back bin/setup in previous state and move gem listen outside test env

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,30 +1,45 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'pathname'
+require 'fileutils'
+include FileUtils
 
-set -e
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
 
-# Setup specific Bundler options if this is CI
-if [ "$CI" ]; then
-  BUNDLER_ARGS="--without development staging production"
-fi
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Make sure we have Bundler installed
-gem install bundler --conservative
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
+  bundler_args = ''
+  bundler_args = '--without development staging production' if ENV.fetch("CI", false)
 
-# Set up Ruby dependencies via Bundler into .bundle folder
-rm -f .bundle/config
+  puts '== Remove .bundle/config =='
+  rm_rf '.bundle/config'
 
-bundle check --path .bundle > /dev/null 2>&1 ||
-  bundle install --path=.bundle $BUNDLER_ARGS
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check --path .bundle') || system!("bundle install --path=.bundle #{bundler_args}")
 
-# Set up configurable environment variables
-if [ ! -f .env ]; then
-  cp .env.example .env
-fi
+  puts "\n== Copying sample files =="
+  unless File.exist?('config/database.yml')
+    cp 'config/database.yml.sample', 'config/database.yml'
+  end
 
-# Set up database and add any development seed data
-bundle exec rails db:create
-bundle exec rails db:schema:load
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:create'
+  system! 'bin/rails db:schema:load'
 
-if [ -z "$CI" ]; then
-  bundle exec rails db:seed
-fi
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  unless ENV.fetch("CI", false)
+    puts "\n== Seeding data =="
+    system! 'bin/rails db:seed'
+  end
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
